var tipuesearch = {"pages": [
     {"title": "El lado bueno de las cosas", "text": "Tras pasar ocho meses en una institucion mental por agredir al amante de su mujer, Pat (Bradley Cooper) vuelve con lo puesto a vivir en casa de sus padres (Robert De Niro y Jacki Weaver). Determinado a tener una actitud positiva y recuperar a su ex-mujer, el mundo de Pat se pone del reves cuando conoce a Tiffany (Jennifer Lawrence), una chica con ciertos problemas y no muy buena fama en el barrio. A pesar de su mutua desconfianza inicial, entre ellos pronto se desarrollara un vinculo muy especial que les ayudara a encontrar en sus vidas el lado bueno de las cosas.", "tags": "pelicula comedia Robert De Niro Bradley Cooper Jennifer Lawrence Jacki Weaver Chris Tucker Julia Stiles Anupam Kher John Ortiz Shea Whigham Dash Mihok Paul Herman Brea Bee David O. Russell", "loc": "pelicula1.html"},
     {"title": "El mayordomo", "text": "Una mirada a la vida de Cecil Gaines (Forest Whitaker), mayordomo jefe de la Casa Blanca durante el mandato de ocho presidentes (1952-1986), lo que le permitió ser testigo directo de la historia política y racial de los Estados Unidos.", "tags": "pelicula drama Forest Whitaker David Oyelowo Oprah Winfrey Cuba Gooding Jr. John Cusack Terrence Howard Lenny Kravitz James Marsden Vanessa Redgrave Alan Rickman Liev Schreiber Robin Williams Jane Fonda Clarence Williams III David Banner Michael Rainey Jr. Alex Pettyfer Mariah Carey Nelsan Ellis Lee Daniels", "loc": "pelicula2.html"},
     {"title": "Una cuestion de tiempo", "text": "Tim Lake (Domhnall Gleeson) es un joven de 21 años que descubre que puede viajar en el tiempo. Su padre (Bill Nighy) le cuenta que todos los hombres de la familia han tenido desde siempre ese don, el de regresar en el tiempo a un momento determinado, una y otra vez, hasta conseguir hacer lo correcto. Así pues, Tim decide volver al pasado a intentar conquistar a Mary (Rachel McAdams), la chica de sus sueños", "tags": "pelicula romantica Domhnall Gleeson Rachel McAdams Bill Nighy Tom Hollander Margot Robbie Rowena Diamond Vanessa Kirby Lindsay Duncan Matt Butcher Lee Asquith-Coe Richard Curtis", "loc": "pelicula3.html"},
     {"title": "Las brujas de zugarramundi", "text": "Dos parados (Mario Casas y Hugo Silva) cometen un atraco y huyen perseguidos por la policía(Pepón Nieto y Secun de la Rosa) y por la ex mujer de uno de ellos (Macarena Gómez). Así, se adentran en los bosques impenetrables de Navarra y caen en las garras de una horda de mujeres enloquecidas que se alimentan de carne humana.", "tags": "pelicula comedia Hugo Silva Mario Casas Carmen Maura,Jaime Ordóñez Terele Pávez Pepón Nieto,Secun de la Rosa Carolina Bang Carlos Areces Gabriel Delgado Macarena Gómez Enrique Villén María Barranco Javier Botet Manuel Tallafé Santiago Segura Alexandra Jiménez Javier Manrique Álex de la Iglesia", "loc": "pelicula5.html"},
     {"title": "Prisioneros", "text": "Keller Dover se enfrenta a la peor pesadilla de un padre. Anna, su hija de seis años, ha desaparecido con su amiga Joy y, a medida que pasa el tiempo, el pánico lo va dominando. Desesperado, decide ocuparse personalmente del asunto. Pero, ¿hasta dónde está dispuesto a llegar para averiguar el paradero de su hija?", "tags": "pelicula drama Denis Villeneuve Hugh Jackman Jake Gyllenhaal Viola Davis Maria Bello Terrence Howard Melissa Leo Paul Dano David Dastmalchian,Dylan Minnette Erin Gerasimovich Kyla Drew Simmons Zoe Soul Len Cariou Wayne Duvall Sandra Ellis Laffert", "loc": "pelicula4.html"},
     {"title": "Cinesa Heron City", "text": "Heron City es el centro de entretenimiento integrado más moderno y emocionante de Europa. En Heron City encontrarás un ambiente que integra la vistosidad de Hollywood con la esencia de la cultura europea en un entorno que se adapta a los gustos y la ajetreada vida moderna, dando posibilidad de elección y flexibilidad a cada persona, en una única localización de acceso gratuito.", "tags": "cine", "loc": "cine.html"},
     {"title": "Cine Roxy A", "text": "Conoce la Cartelera, los Estrenos y Horarios del Cine Roxy A en Madrid.", "tags": "cine", "loc": "cine_roxy_a.html"},
     {"title": "Cines Principe Pio", "text": "Cartelera de estrenos y sesiones para las mejores películas en Principe Pío. Compra online, trailers, eventos en directo, ópera, promociones y más.", "tags": "cine", "loc": "cines_principe_pio.html"},
     {"title": "Cinesa Proyecciones", "text": "Cartelera de estrenos y sesiones para las mejores películas en Proyecciones. Compra online, trailers, eventos en directo, ópera, promociones y más.", "tags": "cine", "loc": "cinesa_proyecciones.html"}
]};